server:
  port: 8888
spring:
  application:
    name: shop-demo
eureka:
  client:
    fetch-registry: true  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: true   # false表示自己不需要向注册中心注册自己
    service-url:
      defaultZone: http://localhost:8099/eureka/
  instance:
    prefer-ip-address: true